apiVersion: v1
kind: Service
metadata:
  name: {{ template "metastore.name" . }}
  labels:
    app: {{ template "metastore.name" . }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.port }} 
  selector:
    app: {{ template "metastore.name" . }}
